image: mcr.microsoft.com/dotnet/core/sdk:3.1

stages:
  - build
  - test
  - deploy

before_script:
  - dotnet --version

# Build
build:
  stage: build
  image: mcr.microsoft.com/dotnet/framework/sdk:4.8
  tags: [windows]
  script:
    - dotnet build AquaCoaster.sln

# Test
test_model:
  stage: test  
  image: mcr.microsoft.com/dotnet/framework/sdk:4.8
  tags: [windows]
  script:
    - dotnet test AquaCoasterTest
